Category.create(name:"Front End")
Category.create(name:"Back End")
Category.create(name:"Logic")
Category.create(name:"Functional")
Category.create(name:"Object Orientated")
Category.create(name:"Data Analytics")
Category.create(name:"Secure Development")
Category.create(name:"Tools")
Category.create(name:"Project Ideas")
Category.create(name:"Network & Internet")
Category.create(name:"Testing")
Category.create(name:"New Tech")
Category.create(name:"Inspiration")
Category.create(name:"Other")
Category.create(name:"N/A")

puts "Category List Added"

Language.create(name:"JavaScript")
Language.create(name:"Python")
Language.create(name:"Java")
Language.create(name:"C++")
Language.create(name:"Swift")
Language.create(name:"Typescript")
Language.create(name:"Go")
Language.create(name:"SQL")
Language.create(name:"Ruby")
Language.create(name:"R")
Language.create(name:"PHP")
Language.create(name:"Perl")
Language.create(name:"Kotlin")
Language.create(name:"C#")
Language.create(name:"Rust")
Language.create(name:".NET")
Language.create(name:"Scheme")
Language.create(name:"Erlang")
Language.create(name:"Scala")
Language.create(name:"Elixir")
Language.create(name:"Haskell")
Language.create(name:"COBOL")
Language.create(name:"HTML")
Language.create(name:"CSS")
Language.create(name:"Other")
Language.create(name:"N/A")

puts "Language Options Added"